[workspace]
members = ["day*", "aoc"]
resolver = "2"

[workspace.package]
authors = ["Sven Groot"]

[workspace.dependencies]
anyhow = "1.0"
bitvec = "1.0.1"
num = "0.4"
text_io = "0.1"
thiserror = "1.0"
aoc = { path = "aoc" }