[package]
name = "day16"
version = "0.1.0"
edition = "2021"
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc.workspace = true
itertools = "0.10.5"
text_io.workspace = true
